### ISSUE TITLE
Ao digitar uma placa e ao listar as placas usar Uppercase

### ISSUE THREAD

**Issue by robsonrosa** [AlexandreSNeto/parking-app#7]
Ao digitar uma placa no campo de busca por placa ou no cadastro de novas placas, seria interessante os campos já exibirem o texto em uppercase.

Da mesma forma, a lista de placas também exibir em uppercase (acho que isso já está sendo feito, pois todas placas que eu vi estavam uppercase).

Ou seja, sempre que aparecer uma placa, ela estará em uppercase.

[uppercase via css](http://www.w3schools.com/cssref/pr_text_text-transform.asp)

**Comment by AlexandreSNeto** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vj3hFt13&#x2F;23-alterar-exibicao-das-placas-para-que-sejam-sempre-em-uppercase"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Alterar exibição das placas para que sejam sempre em uppercase</a>
